language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

dist: trusty
addons:
  chrome: stable

# before_install:  
#  - export CHROME_BIN=/usr/bin/google-chrome
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sudo apt-get update
#  - sudo apt-get install -y libappindicator1 fonts-liberation
#  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#  - sudo dpkg -i google-chrome*.deb

script:
  # First build them to make sure everything is fine
  #- npm run lint
  #- npm run build
  #- npm run publisher

  # Now start testing on testbeds
  # Testbeds are angular2,4,5 projects that we install on in order to make sure it
  # works totally fine as a dependency.
  - sh ./scripts/angular4-test.sh
  - npm run ci

  # Now really build them
  #- npm run build
  #- npm run ci
  #- npm run publisher

after_success:
 - bash ./deploy.sh